mongodb:
  uri: "mongodb://localhost:27017"
  database: "jira_data"
  raw_collection: "issues"
  processed_collection: "processed_data"
  results_collection: "results"
  projects_collection: "projects"
  reports_collection: "reports"

llm:
  model_name: "deepseek-r1:14b"  # Changed from llama3.2
  # model_name: "deepseek-r1:8b"  # Changed from llama3.2
  model_name_small: "deepseek-r1:8b"  
  temperature: 0.5
  max_tokens: 2000
  # base_url: "http://192.168.0.25:11434"
  base_url: "http://127.0.0.1:11434"

embeddings:
  model_name: "all-MiniLM-L6-v2"

clustering:
  algorithm: "kmeans"
  max_clusters: 20

prompts:
  version: 2
  problem_extraction: |
    You are an expert at analyzing customer issues. 
    Your task is to identify problems described in the input text and return the result. 
    Analyze the following text and extract key problem that relate to deployment of Camunda 8 on Azure.
    
    Customer case: 
    "
    {text}
    "

    Instructions:
    1. Identify specific problem that issues was reported for
    2. Note severity (High/Medium/Low)
    3. List potential impact
    
    Please return the extracted problem as in JSON format, like this:
    {{
        "Problem": "<concise problem description>", 
        "Severity": "<level>", 
        "Impact": "<description>" 
      }}

  problem_type: |
    You are an expert in analyzing customer issues. 
    Your task is to identify the type of problem described in the input text below and assign it to one of the existing problem types provided. 
    Always prioritize reusing the most relevant problem type from the existing list. 
    Only create a new problem type if the input text cannot reasonably fit into any of the existing problem types. 
    Reuse from the existing list if possible, or a new problem type if absolutely necessary If creating a new problem type, ensure it is concise, clear, and stated as a single string without any additional explanations, use less then 60 characters.

    Input text:
    {text}

    Existing list of problem types:
    {problem_types}

    Output:
    {{ provide identified problem type here, use 60 characters or less.}}
  problem_type_classification: |
    Given the description: 
    
    {description} 
    
    Classify it into one of the following problem types: 
    {taxonomy}. 
    
    Provide a confidence level between 0-100.
  generate_cluster_summary: |
    You are an expert Product Manager specializing in customer issue analysis. Your task is to generate a single concise summary that synthesizes and captures the essence of the key issues described below.  Avoid listing individual problems; instead, combine them into one overarching and comprehensive statement. Make sure that summary returned is 100 words or less.

    Descriptions of summarized problems:
    
    {descriptions}
  check_relevance: |
    System Instruction: You are a helpful AI Product Manager. You must only reply with "YES" "NO" or "I DON’T KNOW""

    User Instruction: I will provide a text that describes a customer issue. Determine if this text indicates a problem specifically related to customer using AWS or Amazon services.

    {text}
   
paths:
  taxonomy: "./config/taxonomy.yaml"
  templates: "./templates"

vector_store:
  persist_directory: ".\\data\\vectorstore"
  similarity_threshold: 0.85

reports:
  template_dir: "templates"
  output_dir: "data\\results"
  report_filename: "problem_analysis.html"

issue-extractor:
  jira_source: 'text ~ "Azure" and component in (C8-SM, C8-Distribution, C8-Zeebe, C8-Console) AND createdDate >= -365d'
  templates:
    - report_template.html
  data:
    - results
  src:
    - reporting.py
  config:
    - config.yaml
