mongodb:
  uri: "mongodb://localhost:27017"
  database: "issue_extractor"
  raw_collection: "raw_data"
  processed_collection: "processed_data"
  results_collection: "results"

llm:
  model_name: "gpt-4o"
  temperature: 0.1
  max_tokens: 2000

prompts:
  problem_extraction: |
    Given the following context, identify and extract problems:
    Current document: {context.current_doc}
    Similar cases: {context.similar_cases}
    Extract specific problems, their severity, and impact.

paths:
  taxonomy: "./data/taxonomy.json"
  templates: "./templates"

vector_store:
  persist_directory: "./data/vectorstore"
  similarity_threshold: 0.85

reports:
  template_dir: "templates"
  output_dir: "data/results"
  report_filename: "problem_analysis.html"

issue-extractor:
  templates:
    - report_template.html
  data:
    - results
  src:
    - reporting.py
  config:
    - config.yaml
