mongodb:
  uri: "mongodb://localhost:27017"
  database: "jira_data"
  raw_collection: "issues"
  processed_collection: "processed_data"
  results_collection: "results"

llm:
  model_name: "llama3.2"  # Changed from llama3.2
  temperature: 0.1
  max_tokens: 2000

embeddings:
  model_name: "all-MiniLM-L6-v2"

prompts:
  version: 1
  problem_extraction: |
    You are an expert at analyzing customer issues. Your task is to identify problems described in the input text and return the results.
    Analyze the following text and extract key problems.
    
    Customer case: {text}
    
    Similar cases:
    {similar_cases}
    
    Instructions:
    1. Identify specific problems
    2. Note severity (High/Medium/Low)
    3. List potential impact
    
    Please return the extracted problems as a list in JSON format, like this:
    [
      {{
        "Problem": "<problem description>", 
        "Severity": "<level>", 
        "Impact": "<description>" 
      }}
    ]
  problem_type: |
    You are an expert in analyzing customer issues. Your task is to identify the type of problem described in the input text below. 
    Based on the provided list of existing problem types, return your analysis as a concise single string stating just problem type without any additional explanations.

    Input text:
    {text}

    Initial list of problem types:
    {problem_types}

    Output:
    {{Your identified problem type here}}
    

paths:
  taxonomy: "./config/taxonomy.yaml"
  templates: "./templates"

vector_store:
  persist_directory: ".\\data\\vectorstore"
  similarity_threshold: 0.85

reports:
  template_dir: "templates"
  output_dir: "data\\results"
  report_filename: "problem_analysis.html"

issue-extractor:
  templates:
    - report_template.html
  data:
    - results
  src:
    - reporting.py
  config:
    - config.yaml
