problem_types:
- performance and reliability issues
- delivery delays
- technical support
- backup and restore
- data loss
- backup configuration
- procedure clarification
- backup/restore issues
- process configuration issues
- operate issues
- cluster backup failure
- backup scheduling issue
- azure environment incompatibility
- implementation complexity
- backup management issues
- broker configuration issues
- cluster version management
- backup issues
- operational issues
- exporting/importing issues
- api integration issues
- authentication failures
- integration issues
- restore failures
- configuration issues
- upgrade issues
- process data consistency
- cluster data consistency issues
- cloud services limitations
- backup and restore issues
- operate errors
- ui display issues
- backup/restore issues with multitenancy enabled
- backup complexity
- platform integration
- cluster configuration issues
- s3 storage management
- inconsistent data management
- cluster migration
- data backup and storage
- authentication issues
- export issues
- upgrade/deployment issues
- process instance issues
- technical complexity
- data processing issues
- data integrity
- disaster recovery setup
- permission issues
- data recovery issues
- disaster recovery
- api response inconsistencies
- backup failures
- infrastructure failures
- azure documentation issue
- backend errors
- deployment failures
- cloud deployment
- storage limitation
- backup and recovery complexity
- update data integrity
- disk corruption
- component configuration issues
- network storage issues
- performance implications
- performance optimization
- zeebe exporter issues
- deployment complexity
